#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# rally domain settings
host = data.get("host", "")
NEXT_PUBLIC_BASE_URL = "https://"+host

# Testing SMTP Settings on Enviroment
rdb = agent.redis_connect(use_replica=True)
smtp_settings = agent.get_smarthost_settings(rdb)
agent.set_env("SMTP_HOST", smtp_settings['host'])
agent.set_env("SMTP_PORT", smtp_settings['port'])
agent.set_env("SMTP_USER", smtp_settings['username'])
agent.set_env("SMTP_PWD", smtp_settings['password'])
agent.set_env("SMTP_SECURE", smtp_settings['encrypt_smtp'])
agent.set_env("SUPPORT_EMAIL", smtp_settings['username'])
# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()
