#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import json
import sys
# agent is a NethServer library which provides function to communicate with the agent
import agent
import secrets

data = json.load(sys.stdin)

# Setup default values
random_key = secrets.token_hex(32)
SECRET_PASSWORD = data.get("SECRET_PASSWORD",random_key)

def generate_random_password():
    return secrets.token_urlsafe(16)

#Postgres DB
POSTGRES_USER= data.get("POSTGRES_USER", "postgres")
POSTGRES_PASSWORD= generate_random_password()
POSTGRES_DB= data.get("POSTGRES_DB", "rally")

db = {
    "POSTGRES_USER": POSTGRES_USER,
    "POSTGRES_PASSWORD": POSTGRES_PASSWORD,
    "POSTGRES_DB": POSTGRES_DB,
}
agent.write_envfile("database.env", db)
# Make sure everything is saved inside the environment file
DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@postgresql-app:5432/{POSTGRES_DB}"

db_config = {
    "DATABASE_URL": DATABASE_URL,
    "SECRET_PASSWORD": SECRET_PASSWORD,
}
agent.write_envfile("rally-db.env", db_config)
# just before starting systemd unit
agent.dump_env()