#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import os
import json
import sys
# agent is a NethServer library which provides function to communicate with the agent
import agent
import secrets

data = json.load(sys.stdin)

# Setup default values
random_key = secrets.token_hex(32)
SECRET_PASSWORD = data.get("SECRET_PASSWORD",random_key)

# Talk with agent using file descriptor.

agent.set_env("SECRET_PASSWORD", SECRET_PASSWORD)

# Make sure everything is saved inside the environment file
# just before starting systemd unit
agent.dump_env()