#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}
if os.path.exists("rally.env"):
    data = agent.read_envfile("rally.env")
    config["ALLOWED_EMAILS"] = data['ALLOWED_EMAILS']
else:
    config["ALLOWED_EMAILS"] = ""

# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST","")
config["NEXT_PUBLIC_BASE_URL"] = os.getenv("NEXT_PUBLIC_BASE_URL","")
config["NEXTAUTH_URL"] = os.getenv("NEXTAUTH_URL","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"
config["SECRET_PASSWORD"] = os.getenv("SECRET_PASSWORD","")
# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
